config = {'host': 'localhost','database': db, # we got db as an argument'user': 'root','password': 'dude','port': '3306' # change the port to match the port your SQL server is running on} sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") config = {'host': 'localhost','database': xdb, # we got db as an argument'user': 'root','password': 'root','port': '3306' # change the port to match the port your SQL server is running on} File "/Users/frankgenova/Documents/DojoPy0904/Week4/flask_mysql/mysqlconnection.py", line 9, in __init__    'database': xdb, # we got db as an argumentNameError: global name 'xdb' is not defined config = {'host': 'localhost','database': db, # we got db as an argument'user': 'root','password': 'root','port': '8889' # change the port to match the port your SQL server is running on} (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")